import { int, str } from 'env-var-provider';
export { version } from '../package.json';
export const PORT = 'PORT';
export const APP_NAME = 'APP_NAME';
export const MORGAN_FORMAT = 'MORGAN_FORMAT';
export const MORGAN_LOG_FORMAT = 'MORGAN_LOG_FORMAT';
export const SWAGGER_PATH = 'SWAGGER_PATH';
export const FACEBOOK_APP_ID = 'FACEBOOK_APP_ID';
export const FACEBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET';
export const FACEBOOK_APP_TOKEN = 'FACEBOOK_APP_TOKEN';
export const FACEBOOK_API_VERSION = 'FACEBOOK_API_VERSION';
export const JWT_SECRET = 'JWT_SECRET';
export const DEBUG = 'DEBUG';
export const VERSION = 'VERSION';
export const LOG_BUFFER_TIME = 'LOG_BUFFER_TIME';
export const POD_NAME = 'POD_NAME';
export const port = int(PORT, { defaultValue: 80 });
export const appName = str(APP_NAME, { defaultValue: 'UNNAMED SERVICE' });
export const logFormat = str(MORGAN_LOG_FORMAT, { defaultValue: 'dev' });
export const swaggerPath = str(SWAGGER_PATH, { defaultValue: 'doc' });
export const jwtSecret = str(JWT_SECRET, { defaultValue: 'STB' });
